# Generated by Django 2.0 on 2018-10-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('status', models.SmallIntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0, verbose_name='状态')),
                ('priority', models.SmallIntegerField(choices=[(0, 'first'), (1, 'second'), (2, 'third')], default=0, verbose_name='优先级')),
                ('category', models.SmallIntegerField(choices=[(1, '学习'), (2, '锻炼'), (3, '娱乐')], default=1, verbose_name='类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_ontime', models.BooleanField(default=1, verbose_name='是否按时完成')),
                ('startdate', models.DateTimeField(verbose_name='开始时间')),
                ('enddate', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.SmallIntegerField(choices=[(1, '日任务'), (2, '周任务'), (3, '月任务')], verbose_name='时间跨度')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
